### ISSUE TITLE
[Request] Similar mod for Dine

### ISSUE THREAD

**Issue by MiraakThuri** [ButteryStancakes/ArtificeBlizzard#1]
Hey, would it be possible to create something similar to randomly switch between old and new Dine ?

I know that this mod exists https://thunderstore.io/c/lethal-company/p/Dammsugare/OldDine/
but it add old Dine as a completely new moon wich requires tons of external API that can cause mods conflict and does not provide any support for the new enemies and the changes related to balance and power levels

I would love to play old classic flooded and ladder fire exit Dine along with the new more unique looking one

Thx for your great work on the game

**Comment by ButteryStancakes** [comment]
This is unfortunately pretty out of scope. The scene alterations made to Dine were too major for me to restore them like I did with this mod (which just edits Artifice's original scene, rather than loading a different scene file), and adding a new scene would accomplish the same thing as [the mod that already exists.](https://thunderstore.io/c/lethal-company/p/Dammsugare/OldDine/)

I believe LethalLevelLoader lets you configure enemy and scrap spawns for custom moons, if you desire to make them match new Dine

**Comment by MiraakThuri** [comment]
Ah i see, ill try that one with configurable LethalLevelLoader then
Thx
